version: "3.9"

services:
  db:
    image: postgres
    # volumes:
    #   - ./django/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  django:
    build: ./django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  vue:
    build: ./vue
    volumes:
      - ./vue:/app
    ports:
      - "8080:8080"
